# Generated by Django 5.2.8 on 2025-11-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "condiciones_socioeconomicas",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "numero_integrantes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoAyuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("Alimentaria", "Alimentaria"),
                            ("Educativa", "Educativa"),
                            ("Económica", "Económica"),
                            ("Médica", "Médica"),
                            ("Otros", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Voluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Coordinador", "Coordinador"),
                            ("Voluntario", "Voluntario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contacto", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("comentarios", models.TextField(blank=True, null=True)),
                (
                    "evaluacion_impacto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="core.familia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrega", models.DateField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="core.familia",
                    ),
                ),
                (
                    "tipo_ayuda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tipoayuda"
                    ),
                ),
                (
                    "voluntario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.voluntario",
                    ),
                ),
            ],
        ),
    ]
